# Generated by Django 6.1.1 on 2026-09-17 11:52

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=accounts.models.generate_referral_code, max_length=12, unique=True, verbose_name='کد معرف')),
                ('level', models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی')], default='bronze', max_length=10, verbose_name='سطح')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('wallet_balance', models.PositiveIntegerField(default=0, verbose_name='موجودی کیف پول (تومان)')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره موبایل')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('bank_card', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.userprofile', verbose_name='معرف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
