# Generated by Django 6.1.1 on 2026-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بسته')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('support_price', models.PositiveIntegerField(default=0, verbose_name='قیمت تمدید پشتیبانی (تومان)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='مدت پشتیبانی (روز)')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='امتیاز هدیه به خریدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بسته',
                'verbose_name_plural': 'بسته\u200cها',
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
